backend:
  # name: test-repo
  name: git-gateway
  branch: main

#site_url: https://mattausgretzinger.com
#display_url: https://mattausgretzinger.com
display_url: https://magical-figolla-d19d49.netlify.app/

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
# publish_mode: editorial_workflow # For Drafts

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "shows"
    label: "Shows"
    label_singular: "Show"
    folder: "content/shows"
    create: true
    slug: "{{date}}"
    identifier_field: name
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        hint: Name of the show (ex. "Mattaus Gretzinger Quartet").
      - label: "Venue"
        name: "venue"
        widget: "string"
        hint: Name of the venue (ex. "the Rex"). An @ symbol is automatically inserted before the venue name.
      - label: "Address"
        name: "address"
        widget: "string"
        default: "123 Address, Toronto, ON"
        hint: Address of the venue (ex. "942 College Street, Toronto, ON"). The city and province aren't displayed, but it's still important to enter it so that the Google maps link works!
        pattern: ['.*,.*,.*', "Make sure you include the address, city, and province: There should be (at least) two commas"]
      - label: "Show date"
        name: "date"
        widget: "datetime"
        date_format: "dddd MMMM D, YYYY"
        time_format: false
        format: YYYY-MM-DD
      - label: "Show start time"
        name: "start"
        widget: "datetime"
        date_format: false
        time_format: h:mma
        format: "h:mma"
        default: "8:00pm"
      - label: "Show end time"
        name: "end"
        widget: "datetime"
        date_format: false
        time_format: h:mma
        format: "h:mma"
        default: "10:00pm"
      - label: "Description"
        name: "description"
        widget: "markdown"
        buttons: []
        editor_components: []
        modes: [raw]
        hint: You can add more context here, like who's playing or how much it costs to attend.
      - label: "Thumbnail image"
        name: "image"
        widget: "image"