backend:
  name: git-gateway
  repo: owengretzinger/jazz-musician-website
  branch: main

site_url: https://mattausgretzinger.com
display_url: https://mattausgretzinger.com
#display_url: https://magical-figolla-d19d49.netlify.app/

media_folder: "public/images/uploads" # Where media files will be stored
public_folder: "/images/uploads" # Where the media files can be accesed from the server
# publish_mode: editorial_workflow # For Drafts

collections:
  - name: "show-cards"
    label: "Shows"
    label_singular: "Show"
    description: Add information about upcoming shows/gigs
    folder: "content/shows"
    create: true
    slug: "{{date}}-{{start}}"
    identifier_field: date
    summary: "{{date | date('MMMM D')}}: {{title}} @ {{venue}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
        hint: Name of the show (ex. "Mattaus Gretzinger Quartet").
      - label: "Venue"
        name: "venue"
        widget: "string"
        hint: Name of the venue (ex. "the Rex"). An @ symbol is automatically inserted before the venue name.
      - label: "Address"
        name: "address"
        widget: "string"
        default: "123Address, Toronto, ON"
        hint: Address of the venue (ex. "942 College Street, Toronto, ON"). The city and province aren't displayed, but it's still important to enter it so that the Google maps link works!
        pattern:
          [
            ".*,.*,.*",
            "Make sure you include the address, city, and province: There should be (at least) two commas",
          ]
      - label: "Show date"
        name: "date"
        widget: "datetime"
        date_format: "dddd MMMM D, YYYY"
        time_format: false
        format: YYYY-MM-DD
      - label: "Show start time"
        name: "start"
        widget: "datetime"
        date_format: false
        time_format: "H:mma"
        format: "[\"]HHmm[\"]"
        default: '"2000"'
      - label: "Show end time"
        name: "end"
        widget: "datetime"
        date_format: false
        time_format: "H:mma"
        format: "[\"]HHmm[\"]"
        default: '"2200"'
      - label: "Description"
        name: "description"
        widget: "markdown"
        buttons: []
        editor_components: []
        modes: [raw]
        hint: You can add more context here, like who's playing or how much it costs to attend.
      - label: "Thumbnail image"
        name: "image"
        widget: "image"
      - label: "Image anchor"
        name: imagePosition
        widget: select
        options:
          - { label: "top left", value: "object-left-top" }
          - { label: "top middle", value: "object-top" }
          - { label: "top right", value: "object-right-top" }
          - { label: "center left", value: "object-left" }
          - { label: "center middle", value: "object-center" }
          - { label: "center right", value: "object-right" }
          - { label: "bottom left", value: "object-left-bottom" }
          - { label: "bottom middle", value: "object-bottom" }
          - { label: "bottom right", value: "object-right-bottom" }
        default: "object-center"
  - label: "Website Text"
    name: "pages"
    files:
      - label: "About Page"
        name: "about-section"
        file: "content/pages/about.yml"
        fields:
          - { label: Background Image, name: backgroundImage, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Paragraph, name: paragraph, widget: markdown }
          - { label: Card 1 Title, name: cardTitle1, widget: string }
          - { label: Card 1 Image, name: cardImage1, widget: image }
          - label: Card 1 Text
            name: cardText1
            widget: markdown
            buttons: []
            editor_components: []
            modes: [raw]
          - { label: Card 2 Title, name: cardTitle2, widget: string }
          - { label: Card 2 Image, name: cardImage2, widget: image }
          - label: Card 2 Text
            name: cardText2
            widget: markdown
            buttons: []
            editor_components: []
            modes: [raw]
          - { label: Card 3 Title, name: cardTitle3, widget: string }
          - { label: Card 3 Image, name: cardImage3, widget: image }
          - label: Card 3 Text
            name: cardText3
            widget: markdown
            buttons: []
            editor_components: []
            modes: [raw]
      - label: "Videos Page"
        name: "videos-section"
        file: "content/pages/videos.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - label: "Video Links"
            name: "videos"
            widget: "list"
            summary: '{{fields.video}}'
            field: {label: Video Link, name: video, widget: string}
      - label: "Home Page"
        name: "home-section"
        file: "content/pages/home.yml"
        fields:
          - { label: Background Image, name: backgroundImage, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Subtitle, name: subtitle, widget: string }
          - { label: Featured Video Link, name: featuredVideo, widget: string }
      - label: "Shows Page"
        name: "shows-section"
        file: "content/pages/shows.yml"
        fields:
          - { label: Upcoming Shows Text, name: title1, widget: string }
          - label: No Upcoming Shows Text
            name: noUpcoming
            widget: markdown
            buttons: []
            editor_components: []
            modes: [raw]
          - { label: Past Shows Text, name: title2, widget: string }
      - label: "Contact Page"
        name: "contact-section"
        file: "content/pages/contact.yml"
        fields:
          - { label: Title, name: title, widget: string }
          - label: Blurb
            name: blurb
            widget: markdown
            buttons: []
            editor_components: []
            modes: [raw]
          - { label: Instagram Link, name: instagram, widget: string, hint: Also used for the home page }
          - { label: Youtube Link, name: youtube, widget: string, hint: Also used for the home page }
          - { label: Email Link, name: email, widget: string, hint: Also used for the home page }

