backend:
  name: git-gateway
  branch: main

#site_url: https://mattausgretzinger.com
#display_url: https://mattausgretzinger.com
display_url: https://magical-figolla-d19d49.netlify.app/

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
# publish_mode: editorial_workflow # For Drafts

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "content/blogs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", date_format: "DD.MM.YYYY", time_format: "HH:mm", format: "LLL"}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "gig"
    label: "Gig"
    folder: "content/gigs"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime", time_format: false}
      - {label: "Start Time", name: "start", widget: "datetime", date_format: false}
      - {label: "End Time", name: "end", widget: "datetime", date_format: false}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Address", name: "address", widget: "string"}